export enum ComponentType {
    Animator = "ANIMATOR_COMPONENT",
    TRANSFORM = "TRANSFORM_COMPONENT",
    CAMERA = "CAMERA_COMPONENT",
    ANIMATOR_CONTROLLER = "ANIMATOR_CONTROLLER_COMPONENT",
    CHARACTER_CONTROLLER = "CHARACTER_CONTROLLER_COMPONENT",
    SPRITE_RENDER = "SPRITE_RENDER_COMPONENT",
    BOX_COLLIDER = "BOX_COLLIDER_COMPONENT",
    COLLIDER = "COLLIDER_COMPONENT",
    CIRCLE_COLLIDER = "CIRCLE_COLLIDER_COMPONENT",
    RigidBody = "RigidBody"
}